version: "3"

services:
  fastapi:
    build: .
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - celery

  celery:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: celery -A send_mail.celery worker -l INFO

  redis:
    image: redis:6-alpine
